spring:
  application:
    name: pragati-backend

  # PostgreSQL configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/pragati_db
    username: postgres
    password: system # Update with your local database password
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

jwt:
  # Base64 string for test purposes
  secret: Y2F1dGlvbmFyeS1zaWduLWhvbWV3b3JrLXRlYWNoZXItZ3VpdGFyLWZsb3dlci12aWxsYWdlci1zZWN1cmUta2V5LXByYWdhdGktMjAyNg==
  expiration: 86400000 # 1 day in milliseconds

server:
  port: 8080
